print("--------------------------")
print("Mootod Naimai VAT INVOICE")
print("--------------------------")
print("MooTod + Rice x 1  : 60  THB ")
print("Water         x 1  : 15  THB ")
print("Mango         x 1  : 30  THB ")
print("Kaitod        x 10 : 250 THB ")
print("SET A         x 1  : 350 THB ")
print("SET B         x 1  : 400 THB ")
print("BIG Set       x 1  : 555 THB ")
print("Happy FryDay  x 1  : 200 THB ")
print("--------------------------")
print("Total              : 1860 THB ")